### ISSUE TITLE
SmallBrothery.py - Main instance has no attribute 'logger'

### ISSUE THREAD

**Issue by hhiru** [benbaptist/minecraft-wrapper#284]
Tried to use this plugin from the example folder but I have this error (sorry for all these issues):

[21:36:54] [Wrapper.py/INFO] Loading plugins... 
[21:36:54] [Wrapper.py/INFO] Loading plugin SmallBrother.py... 
[21:38:53] [Wrapper.py/ERROR] Plugin 'com.benbaptist.plugins.smallbrother' errored out when executing callback event 'timer.second': 
[21:38:53] [Wrapper.py/ERROR] Traceback (most recent call last): 
[21:38:53] [Wrapper.py/ERROR]   File "Wrapper.py\__main__.py", line 139, in callEvent 
[21:38:53] [Wrapper.py/ERROR]     result = self.events[pluginID][event](payload) 
[21:38:53] [Wrapper.py/ERROR]   File "wrapper-plugins\SmallBrother.py", line 35, in timer 
[21:38:53] [Wrapper.py/ERROR]     self.logger.flush() 
[21:38:53] [Wrapper.py/ERROR] AttributeError: Main instance has no attribute 'logger' 
[21:38:53] [Wrapper.py/ERROR]

**Comment by suresttexas00** [comment]
I already have a issue open on this #240

**Comment by suresttexas00** [comment]
This is caused by
```
    def onEnable(self):
        self.api.registerEvent("player.dig", self.breakBlock)
        self.api.registerEvent("player.place", self.placeBlock)
        self.api.registerEvent("timer.second", self.timer)
        
        self.api.registerEvent("server.started", self.onServerStart)
        
        self.api.registerCommand("sb", self._sb)
        if self.minecraft.isServerStarted():
            self.onServerStart({})

    def onDisable(self):
        self.logger.flush()

    def onServerStart(self, payload):
        self.logger = Logger(self.minecraft.getWorldName())
        self.logger.init()

    def timer(self, payload):
        self.time += 1
        if self.time == 60 * 2:
            self.logger.flush()
            self.time = 0
```

The plugin is enabled (and the timer starts couting) when wrapper starts, but the logger instance is not created until the server is fully started.  This particular error just needs a couple lines added to the timer:
```
        if not self.minecraft.isServerStarted():
            return
```

I'll put this in the next set of fixes. 

One thing about this plugin: It is hard - coded for 1.8 and won't work on 1.9.  I can upgrade it, but it will break wrapper backwards compatibility.

**Comment by suresttexas00** [comment]
#312
