### ISSUE TITLE
misc Error in the Server->Client method:

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#168]
I don't have the context for when this occurred, but I thought I would mention it to see if there might be some sort of sytax error or misspelling or case issue (UUID versus uuid), etc
...

```
Error in the Server->Client method:
Traceback (most recent call last):
  File "Wrapper\proxy.py", line 860, in handle
    if self.parse(id, original) and self.safe:
  File "Wrapper\proxy.py", line 702, in parse
    self.proxy.getClientByServerUUID(data["uuid"]).uuid,
AttributeError: 'UUID' object has no attribute 'uuid'
```

**Comment by benbaptist** [comment]
Looking at this error just reminds me of how bad proxy.py is written. It was done at a whim, the naming conventions and such make no sense, it's unorganized as could be, and it's more rickety than a wooden bridge that was just lit on fire. It's in desperate need for a re-write from scratch. If done right, it'll probably remove most of these reall weird quirks.

**Comment by suresttexas00** [comment]
Well, sometimes you just have to get something working and make it pretty later...

**Comment by suresttexas00** [comment]
The non-specificity of this error and the recent work to proxy.py warrants closing the thread.
